import { VisitListContainer } from "../visits/types";
import { MockData } from "./types";


const visits: VisitListContainer = {
  "LaterVisitsList": [
    {
      "HasPaymentFeature": true,
      "HasQuestionnaireFeature": true,
      "HasNewPvdFeature": false,
      "PrimaryDate": "1/1/2050 09:00:00 AM",
      "CsnForECheckIn": "FAKE_CSN_0",
      "RescheduledDatString": null,
      "IsNoShow": false,
      "LeftWithoutSeen": false,
      "DischargeDate": null,
      "HasDownloadSummaryLink": false,
      "HasTransmitSummaryLink": false,
      "CanRedirectToApptDetails": false,
      "PastVisitBucket": null,
      "IsClinicalInformationAvailable": false,
      "OwnedBy": 0,
      "AdmissionDateRange": null,
      "IsApptDetailsEnabled": true,
      "IsRequestCancelEnabled": true,
      "IsDirectCancelEnabled": true,
      "IsRescheduleEnabled": true,
      "IsCopayEnabled": true,
      "IsVisitSummaryEnabled": true,
      "IsDownloadSummaryEnabled": true,
      "IsTransmitCEEnabled": true,
      "IsTransmitDirectEnabled": false,
      "IsDischargeInstrEnabled": true,
      "IsPatHandoutsEnabled": false,
      "IsIPReviewEnabled": false,
      "IsDischargeSummaryEnabled": true,
      "IsProviderLinkEnabled": true,
      "IsPreadmissionEnabled": true,
      "IsEcheckInCompleted": false,
      "Csn": "FAKE_CSN_0",
      "Id": "FAKE_ID_0",
      "ReferenceID": "",
      "OrganizationLinks": [],
      "PrimaryOrganizationLink": null,
      "Organization": {
        "OrganizationId": "FAKE_ORG_ID",
        "OrganizationIdentifier": null,
        "RelatedOrganizations": null,
        "HasChildOrgs": false,
        "CELocationId": null,
        "WebsiteName": null,
        "OrganizationName": "FAKE Health Organization",
        "MyChartAppName": null,
        "SsnLabel": null,
        "IsLocal": true,
        "LogoUrl": "https://fakeorg.example.com/logo.png",
        "TermsAndConditionsUrl": null,
        "ProxyTermsAndConditionsUrl": null,
        "Address": [
          "FAKE_PHONE_0",
          "123 Fake Street",
          "Suite 100",
          "Fake City, FC 12345",
          "Fakeland"
        ],
        "DisplayAddress": null,
        "ContactInformation": null,
        "UrlList": null,
        "IsSSO": false,
        "IncompleteH2GSetup": false,
        "LastEncounterInfo": null,
        "IsGeneric": false,
        "PayerOrgDetails": {
          "IsPayerOnly": false,
          "IsPayvider": false,
          "IsPayer": false,
          "IsPayerLicensedForMyChart": false,
          "PayerChildWebsiteName": "",
          "PayerCvgLogo": "FAKE_PAYER_LOGO",
          "PayerCvgLogoMagicId": null,
          "PayerCvgToken": "FAKE_PAYER_TOKEN",
          "PayerCvgName": "FAKE_PAYER_NAME"
        },
        "IsMyChartCentral": false
      },
      "EncodedOrgID": null,
      "Month": 1,
      "DateOfMonth": "1",
      "Year": "2050",
      "IsLocal": true,
      "IsNonEpic": false,
      "IsSingleProvider": true,
      "Telemedicine": null,
      "EVisit": null,
      "CanShowTelemedicine": false,
      "Dat": "FAKE_DAT_0",
      "Date": "Friday January 01, 2050",
      "Time": "09:00 AM",
      "IsAM": true,
      "IsClientTime": false,
      "ClientTimeZoneMarker": "EDT",
      "EncounterType": 1,
      "VisitTypeName": "Fake Procedure A",
      "Instant": "/Date(2524608000000)/",
      "ArrivalTime": "08:45 AM",
      "CanShowArrivalTime": true,
      "EarlyArrivalReason": "",
      "DurationInMinutes": null,
      "HasDuration": false,
      "Copay": null,
      "CanShowPayments": false,
      "ShortDate": "01/01/50",
      "IsTimeToBeDetermined": false,
      "IsHideVisitTime": false,
      "CanShowAppointmentTime": true,
      "TimeZone": "EDT",
      "Providers": [],
      "OtherProviders": [],
      "NumberOfOthers": 0,
      "PrimaryProvider": null,
      "PrimaryProviderName": null,
      "PrimaryDepartment": {
        "Id": "FAKE_DEPT_0",
        "Name": "Fake Department A",
        "Address": [
          "123 Department Ave",
          "Fake Town, FC 11111"
        ],
        "HasAddress": true,
        "PhoneNumber": "FAKE_PHONE_DEPT_0",
        "Instructions": [],
        "ShouldShowInstructions": false,
        "TimeZone": "EDT",
        "ArrivalLocation": "",
        "Specialty": {
          "Value": "00",
          "Title": "General",
          "TitleUtf8": null,
          "Abbreviation": "Gen"
        },
        "CanShowDrivingDirections": true,
        "IsPreadmissionLocation": false
      },
      "CanRequestCancel": false,
      "IsCanceled": false,
      "CanReschedule": false,
      "RescheduledDat": "",
      "IsDetailsEnabled": true,
      "ECheckIn": {
        "Status": {
          "Value": "",
          "Title": "",
          "Abbreviation": ""
        },
        "IsNotStarted": false,
        "IsInProgress": false,
        "IsComplete": false,
        "Barcode": "",
        "HasBarcodeStep": false,
        "ClinicSteps": [],
        "ECheckInSteps": [],
        "HasQuestionnaireLink": false,
        "IsAdmission": false,
        "IsSurgery": false,
        "IsQnrAfterBarcode": false,
        "IsConfirmationView": false,
        "SignUpLink": null,
        "HasSignUpLink": false,
        "IsRequiredForTelemedicine": false,
        "CanShow": false,
        "HasPaymentECheckInStep": false,
        "HasQuestionnaireStep": false,
        "IsInHelloPatientWindow": false
      },
      "CanShowECheckIn": false,
      "CanShowECheckInComplete": false,
      "IsECheckInComplete": false,
      "NextIncompleteVisitECheckInCsn": null,
      "IsEcheckInEnabled": true,
      "IsECheckInIncomplete": false,
      "CanECheckIn": false,
      "ShouldShowECheckInInGuideBanner": false,
      "CanShowAddToCalendar": true,
      "IsPastVisit": false,
      "HighlightDate": "1/1/2050",
      "IsDrivingDirectionsEnabled": true,
      "ConfirmationStatus": 2,
      "IsConfirmed": false,
      "IsCancelRequestSent": false,
      "CanDirectlyCancel": false,
      "IsUsingFallbackVisitTypeName": false,
      "ChiefComplaint": "",
      "Diagnoses": null,
      "HasSentUpgradeRequest": false,
      "CanSendUpgradeRequest": false,
      "IsUserInitiatedArrivalAllowed": false,
      "SelfArrivalMechanism": 0,
      "SelfArrivalBannerViewModel": null,
      "GeolocationArrival": 0,
      "ArrivalStatus": 0,
      "PatientNextStepInstructions": "",
      "ArrivalAdditionalActions": [],
      "IsProxyRequestMinorFormOn": false,
      "ProxyRequestMinorForm": "",
      "GuestPatientFirstName": null,
      "TelehealthMode": 0,
      "InProgress": false,
      "IsResidentialMed": false,
      "EncounterIsSurgery": false,
      "EncounterIsEDVisit": false,
      "IsPreadmission": false,
      "SurgeryTimeOfDay": null,
      "PreadmissionLocation": null,
      "Cases": null,
      "IsHovPreadmission": false,
      "HasProcedures": false,
      "NumberOfProcedures": 0,
      "SurgicalProcedures": null,
      "ComponentVisits": null,
      "HasComponentVisits": false,
      "HasPaymentInfo": false,
      "IsFullyPaid": true,
      "CompleteECheckInCount": 0,
      "TotalECheckInCount": 0
    },
    {
      "HasPaymentFeature": true,
      "HasQuestionnaireFeature": true,
      "HasNewPvdFeature": false,
      "PrimaryDate": "1/1/2050 09:15:00 AM",
      "CsnForECheckIn": "FAKE_CSN_1",
      "RescheduledDatString": null,
      "IsNoShow": false,
      "LeftWithoutSeen": false,
      "DischargeDate": null,
      "HasDownloadSummaryLink": false,
      "HasTransmitSummaryLink": false,
      "CanRedirectToApptDetails": false,
      "PastVisitBucket": null,
      "IsClinicalInformationAvailable": false,
      "OwnedBy": 0,
      "AdmissionDateRange": null,
      "IsApptDetailsEnabled": true,
      "IsRequestCancelEnabled": true,
      "IsDirectCancelEnabled": true,
      "IsRescheduleEnabled": true,
      "IsCopayEnabled": true,
      "IsVisitSummaryEnabled": true,
      "IsDownloadSummaryEnabled": true,
      "IsTransmitCEEnabled": true,
      "IsTransmitDirectEnabled": false,
      "IsDischargeInstrEnabled": true,
      "IsPatHandoutsEnabled": false,
      "IsIPReviewEnabled": false,
      "IsDischargeSummaryEnabled": true,
      "IsProviderLinkEnabled": true,
      "IsPreadmissionEnabled": true,
      "IsEcheckInCompleted": false,
      "Csn": "FAKE_CSN_1",
      "Id": "FAKE_ID_1",
      "ReferenceID": "",
      "OrganizationLinks": [],
      "PrimaryOrganizationLink": null,
      "Organization": {
        "OrganizationId": "FAKE_ORG_ID",
        "OrganizationIdentifier": null,
        "RelatedOrganizations": null,
        "HasChildOrgs": false,
        "CELocationId": null,
        "WebsiteName": null,
        "OrganizationName": "FAKE Health Organization",
        "MyChartAppName": null,
        "SsnLabel": null,
        "IsLocal": true,
        "LogoUrl": "https://fakeorg.example.com/logo.png",
        "TermsAndConditionsUrl": null,
        "ProxyTermsAndConditionsUrl": null,
        "Address": [
          "FAKE_PHONE_0",
          "123 Fake Street",
          "Suite 100",
          "Fake City, FC 12345",
          "Fakeland"
        ],
        "DisplayAddress": null,
        "ContactInformation": null,
        "UrlList": null,
        "IsSSO": false,
        "IncompleteH2GSetup": false,
        "LastEncounterInfo": null,
        "IsGeneric": false,
        "PayerOrgDetails": {
          "IsPayerOnly": false,
          "IsPayvider": false,
          "IsPayer": false,
          "IsPayerLicensedForMyChart": false,
          "PayerChildWebsiteName": "",
          "PayerCvgLogo": "FAKE_PAYER_LOGO",
          "PayerCvgLogoMagicId": null,
          "PayerCvgToken": "FAKE_PAYER_TOKEN",
          "PayerCvgName": "FAKE_PAYER_NAME"
        },
        "IsMyChartCentral": false
      },
      "EncodedOrgID": null,
      "Month": 1,
      "DateOfMonth": "1",
      "Year": "2050",
      "IsLocal": true,
      "IsNonEpic": false,
      "IsSingleProvider": true,
      "Telemedicine": null,
      "EVisit": null,
      "CanShowTelemedicine": false,
      "Dat": "FAKE_DAT_1",
      "Date": "Friday January 01, 2050",
      "Time": "09:15 AM",
      "IsAM": true,
      "IsClientTime": false,
      "ClientTimeZoneMarker": "EDT",
      "EncounterType": 1,
      "VisitTypeName": "Fake Procedure B",
      "Instant": "/Date(2524608900000)/",
      "ArrivalTime": "09:00 AM",
      "CanShowArrivalTime": true,
      "EarlyArrivalReason": "",
      "DurationInMinutes": null,
      "HasDuration": false,
      "Copay": null,
      "CanShowPayments": false,
      "ShortDate": "01/01/50",
      "IsTimeToBeDetermined": false,
      "IsHideVisitTime": false,
      "CanShowAppointmentTime": true,
      "TimeZone": "EDT",
      "Providers": [],
      "OtherProviders": [],
      "NumberOfOthers": 0,
      "PrimaryProvider": null,
      "PrimaryProviderName": null,
      "PrimaryDepartment": {
        "Id": "FAKE_DEPT_1",
        "Name": "Fake Department B",
        "Address": [
          "123 Department Ave",
          "Fake Town, FC 11111"
        ],
        "HasAddress": true,
        "PhoneNumber": "FAKE_PHONE_DEPT_1",
        "Instructions": [],
        "ShouldShowInstructions": false,
        "TimeZone": "EDT",
        "ArrivalLocation": "",
        "Specialty": {
          "Value": "00",
          "Title": "General",
          "TitleUtf8": null,
          "Abbreviation": "Gen"
        },
        "CanShowDrivingDirections": true,
        "IsPreadmissionLocation": false
      },
      "CanRequestCancel": false,
      "IsCanceled": false,
      "CanReschedule": false,
      "RescheduledDat": "",
      "IsDetailsEnabled": true,
      "ECheckIn": {
        "Status": {
          "Value": "",
          "Title": "",
          "Abbreviation": ""
        },
        "IsNotStarted": false,
        "IsInProgress": false,
        "IsComplete": false,
        "Barcode": "",
        "HasBarcodeStep": false,
        "ClinicSteps": [],
        "ECheckInSteps": [],
        "HasQuestionnaireLink": false,
        "IsAdmission": false,
        "IsSurgery": false,
        "IsQnrAfterBarcode": false,
        "IsConfirmationView": false,
        "SignUpLink": null,
        "HasSignUpLink": false,
        "IsRequiredForTelemedicine": false,
        "CanShow": false,
        "HasPaymentECheckInStep": false,
        "HasQuestionnaireStep": false,
        "IsInHelloPatientWindow": false
      },
      "CanShowECheckIn": false,
      "CanShowECheckInComplete": false,
      "IsECheckInComplete": false,
      "NextIncompleteVisitECheckInCsn": null,
      "IsEcheckInEnabled": true,
      "IsECheckInIncomplete": false,
      "CanECheckIn": false,
      "ShouldShowECheckInInGuideBanner": false,
      "CanShowAddToCalendar": true,
      "IsPastVisit": false,
      "HighlightDate": "1/1/2050",
      "IsDrivingDirectionsEnabled": true,
      "ConfirmationStatus": 2,
      "IsConfirmed": false,
      "IsCancelRequestSent": false,
      "CanDirectlyCancel": false,
      "IsUsingFallbackVisitTypeName": false,
      "ChiefComplaint": "",
      "Diagnoses": null,
      "HasSentUpgradeRequest": false,
      "CanSendUpgradeRequest": false,
      "IsUserInitiatedArrivalAllowed": false,
      "SelfArrivalMechanism": 0,
      "SelfArrivalBannerViewModel": null,
      "GeolocationArrival": 0,
      "ArrivalStatus": 0,
      "PatientNextStepInstructions": "",
      "ArrivalAdditionalActions": [],
      "IsProxyRequestMinorFormOn": false,
      "ProxyRequestMinorForm": "",
      "GuestPatientFirstName": null,
      "TelehealthMode": 0,
      "InProgress": false,
      "IsResidentialMed": false,
      "EncounterIsSurgery": false,
      "EncounterIsEDVisit": false,
      "IsPreadmission": false,
      "SurgeryTimeOfDay": null,
      "PreadmissionLocation": null,
      "Cases": null,
      "IsHovPreadmission": false,
      "HasProcedures": false,
      "NumberOfProcedures": 0,
      "SurgicalProcedures": null,
      "ComponentVisits": null,
      "HasComponentVisits": false,
      "HasPaymentInfo": false,
      "IsFullyPaid": true,
      "CompleteECheckInCount": 0,
      "TotalECheckInCount": 0
    },
    {
      "HasPaymentFeature": true,
      "HasQuestionnaireFeature": true,
      "HasNewPvdFeature": false,
      "PrimaryDate": "1/2/2050 10:00:00 AM",
      "CsnForECheckIn": "FAKE_CSN_2",
      "RescheduledDatString": null,
      "IsNoShow": false,
      "LeftWithoutSeen": false,
      "DischargeDate": null,
      "HasDownloadSummaryLink": false,
      "HasTransmitSummaryLink": false,
      "CanRedirectToApptDetails": false,
      "PastVisitBucket": null,
      "IsClinicalInformationAvailable": false,
      "OwnedBy": 0,
      "AdmissionDateRange": null,
      "IsApptDetailsEnabled": true,
      "IsRequestCancelEnabled": true,
      "IsDirectCancelEnabled": true,
      "IsRescheduleEnabled": true,
      "IsCopayEnabled": true,
      "IsVisitSummaryEnabled": true,
      "IsDownloadSummaryEnabled": true,
      "IsTransmitCEEnabled": true,
      "IsTransmitDirectEnabled": false,
      "IsDischargeInstrEnabled": true,
      "IsPatHandoutsEnabled": false,
      "IsIPReviewEnabled": false,
      "IsDischargeSummaryEnabled": true,
      "IsProviderLinkEnabled": true,
      "IsPreadmissionEnabled": true,
      "IsEcheckInCompleted": false,
      "Csn": "FAKE_CSN_2",
      "Id": "FAKE_ID_2",
      "ReferenceID": "",
      "OrganizationLinks": [],
      "PrimaryOrganizationLink": null,
      "Organization": {
        "OrganizationId": "FAKE_ORG_ID",
        "OrganizationIdentifier": null,
        "RelatedOrganizations": null,
        "HasChildOrgs": false,
        "CELocationId": null,
        "WebsiteName": null,
        "OrganizationName": "FAKE Health Organization",
        "MyChartAppName": null,
        "SsnLabel": null,
        "IsLocal": true,
        "LogoUrl": "https://fakeorg.example.com/logo.png",
        "TermsAndConditionsUrl": null,
        "ProxyTermsAndConditionsUrl": null,
        "Address": [
          "FAKE_PHONE_0",
          "123 Fake Street",
          "Suite 100",
          "Fake City, FC 12345",
          "Fakeland"
        ],
        "DisplayAddress": null,
        "ContactInformation": null,
        "UrlList": null,
        "IsSSO": false,
        "IncompleteH2GSetup": false,
        "LastEncounterInfo": null,
        "IsGeneric": false,
        "PayerOrgDetails": {
          "IsPayerOnly": false,
          "IsPayvider": false,
          "IsPayer": false,
          "IsPayerLicensedForMyChart": false,
          "PayerChildWebsiteName": "",
          "PayerCvgLogo": "FAKE_PAYER_LOGO",
          "PayerCvgLogoMagicId": null,
          "PayerCvgToken": "FAKE_PAYER_TOKEN",
          "PayerCvgName": "FAKE_PAYER_NAME"
        },
        "IsMyChartCentral": false
      },
      "EncodedOrgID": null,
      "Month": 1,
      "DateOfMonth": "2",
      "Year": "2050",
      "IsLocal": true,
      "IsNonEpic": false,
      "IsSingleProvider": true,
      "Telemedicine": null,
      "EVisit": null,
      "CanShowTelemedicine": false,
      "Dat": "FAKE_DAT_2",
      "Date": "Saturday January 02, 2050",
      "Time": "10:00 AM",
      "IsAM": true,
      "IsClientTime": false,
      "ClientTimeZoneMarker": "EDT",
      "EncounterType": 1,
      "VisitTypeName": "Fake Procedure C",
      "Instant": "/Date(2524694400000)/",
      "ArrivalTime": null,
      "CanShowArrivalTime": false,
      "EarlyArrivalReason": null,
      "DurationInMinutes": null,
      "HasDuration": false,
      "Copay": null,
      "CanShowPayments": false,
      "ShortDate": "01/02/50",
      "IsTimeToBeDetermined": false,
      "IsHideVisitTime": false,
      "CanShowAppointmentTime": true,
      "TimeZone": "EDT",
      "Providers": [],
      "OtherProviders": [],
      "NumberOfOthers": 0,
      "PrimaryProvider": null,
      "PrimaryProviderName": null,
      "PrimaryDepartment": {
        "Id": "FAKE_DEPT_2",
        "Name": "Fake Department C",
        "Address": [
          "123 Department Ave",
          "Fake Town, FC 11111"
        ],
        "HasAddress": true,
        "PhoneNumber": "FAKE_PHONE_DEPT_2",
        "Instructions": [],
        "ShouldShowInstructions": false,
        "TimeZone": "EDT",
        "ArrivalLocation": "",
        "Specialty": {
          "Value": "00",
          "Title": "General",
          "TitleUtf8": null,
          "Abbreviation": "Gen"
        },
        "CanShowDrivingDirections": true,
        "IsPreadmissionLocation": false
      },
      "CanRequestCancel": false,
      "IsCanceled": false,
      "CanReschedule": false,
      "RescheduledDat": "",
      "IsDetailsEnabled": true,
      "ECheckIn": {
        "Status": {
          "Value": "",
          "Title": "",
          "Abbreviation": ""
        },
        "IsNotStarted": false,
        "IsInProgress": false,
        "IsComplete": false,
        "Barcode": "",
        "HasBarcodeStep": false,
        "ClinicSteps": [],
        "ECheckInSteps": [],
        "HasQuestionnaireLink": false,
        "IsAdmission": false,
        "IsSurgery": false,
        "IsQnrAfterBarcode": false,
        "IsConfirmationView": false,
        "SignUpLink": null,
        "HasSignUpLink": false,
        "IsRequiredForTelemedicine": false,
        "CanShow": false,
        "HasPaymentECheckInStep": false,
        "HasQuestionnaireStep": false,
        "IsInHelloPatientWindow": false
      },
      "CanShowECheckIn": false,
      "CanShowECheckInComplete": false,
      "IsECheckInComplete": false,
      "NextIncompleteVisitECheckInCsn": null,
      "IsEcheckInEnabled": true,
      "IsECheckInIncomplete": false,
      "CanECheckIn": false,
      "ShouldShowECheckInInGuideBanner": false,
      "CanShowAddToCalendar": true,
      "IsPastVisit": false,
      "HighlightDate": "1/2/2050",
      "IsDrivingDirectionsEnabled": true,
      "ConfirmationStatus": 2,
      "IsConfirmed": false,
      "IsCancelRequestSent": false,
      "CanDirectlyCancel": false,
      "IsUsingFallbackVisitTypeName": false,
      "ChiefComplaint": "",
      "Diagnoses": null,
      "HasSentUpgradeRequest": false,
      "CanSendUpgradeRequest": false,
      "IsUserInitiatedArrivalAllowed": false,
      "SelfArrivalMechanism": 0,
      "SelfArrivalBannerViewModel": null,
      "GeolocationArrival": 0,
      "ArrivalStatus": 0,
      "PatientNextStepInstructions": "",
      "ArrivalAdditionalActions": [],
      "IsProxyRequestMinorFormOn": false,
      "ProxyRequestMinorForm": "",
      "GuestPatientFirstName": null,
      "TelehealthMode": 0,
      "InProgress": false,
      "IsResidentialMed": false,
      "EncounterIsSurgery": false,
      "EncounterIsEDVisit": false,
      "IsPreadmission": false,
      "SurgeryTimeOfDay": null,
      "PreadmissionLocation": null,
      "Cases": null,
      "IsHovPreadmission": false,
      "HasProcedures": false,
      "NumberOfProcedures": 0,
      "SurgicalProcedures": null,
      "ComponentVisits": null,
      "HasComponentVisits": false,
      "HasPaymentInfo": false,
      "IsFullyPaid": true,
      "CompleteECheckInCount": 0,
      "TotalECheckInCount": 0
    },
    {
      "HasPaymentFeature": true,
      "HasQuestionnaireFeature": true,
      "HasNewPvdFeature": false,
      "PrimaryDate": "1/3/2050 11:00:00 AM",
      "CsnForECheckIn": "FAKE_CSN_3",
      "RescheduledDatString": null,
      "IsNoShow": false,
      "LeftWithoutSeen": false,
      "DischargeDate": null,
      "HasDownloadSummaryLink": false,
      "HasTransmitSummaryLink": false,
      "CanRedirectToApptDetails": false,
      "PastVisitBucket": null,
      "IsClinicalInformationAvailable": false,
      "OwnedBy": 0,
      "AdmissionDateRange": null,
      "IsApptDetailsEnabled": true,
      "IsRequestCancelEnabled": true,
      "IsDirectCancelEnabled": true,
      "IsRescheduleEnabled": true,
      "IsCopayEnabled": true,
      "IsVisitSummaryEnabled": true,
      "IsDownloadSummaryEnabled": true,
      "IsTransmitCEEnabled": true,
      "IsTransmitDirectEnabled": false,
      "IsDischargeInstrEnabled": true,
      "IsPatHandoutsEnabled": false,
      "IsIPReviewEnabled": false,
      "IsDischargeSummaryEnabled": true,
      "IsProviderLinkEnabled": true,
      "IsPreadmissionEnabled": true,
      "IsEcheckInCompleted": false,
      "Csn": "FAKE_CSN_3",
      "Id": "FAKE_ID_3",
      "ReferenceID": "",
      "OrganizationLinks": [],
      "PrimaryOrganizationLink": null,
      "Organization": {
        "OrganizationId": "FAKE_ORG_ID",
        "OrganizationIdentifier": null,
        "RelatedOrganizations": null,
        "HasChildOrgs": false,
        "CELocationId": null,
        "WebsiteName": null,
        "OrganizationName": "FAKE Health Organization",
        "MyChartAppName": null,
        "SsnLabel": null,
        "IsLocal": true,
        "LogoUrl": "https://fakeorg.example.com/logo.png",
        "TermsAndConditionsUrl": null,
        "ProxyTermsAndConditionsUrl": null,
        "Address": [
          "FAKE_PHONE_0",
          "123 Fake Street",
          "Suite 100",
          "Fake City, FC 12345",
          "Fakeland"
        ],
        "DisplayAddress": null,
        "ContactInformation": null,
        "UrlList": null,
        "IsSSO": false,
        "IncompleteH2GSetup": false,
        "LastEncounterInfo": null,
        "IsGeneric": false,
        "PayerOrgDetails": {
          "IsPayerOnly": false,
          "IsPayvider": false,
          "IsPayer": false,
          "IsPayerLicensedForMyChart": false,
          "PayerChildWebsiteName": "",
          "PayerCvgLogo": "FAKE_PAYER_LOGO",
          "PayerCvgLogoMagicId": null,
          "PayerCvgToken": "FAKE_PAYER_TOKEN",
          "PayerCvgName": "FAKE_PAYER_NAME"
        },
        "IsMyChartCentral": false
      },
      "EncodedOrgID": null,
      "Month": 1,
      "DateOfMonth": "3",
      "Year": "2050",
      "IsLocal": true,
      "IsNonEpic": false,
      "IsSingleProvider": true,
      "Telemedicine": null,
      "EVisit": null,
      "CanShowTelemedicine": false,
      "Dat": "FAKE_DAT_3",
      "Date": "Sunday January 03, 2050",
      "Time": "11:00 AM",
      "IsAM": true,
      "IsClientTime": false,
      "ClientTimeZoneMarker": "EDT",
      "EncounterType": 1,
      "VisitTypeName": "Fake Procedure D",
      "Instant": "/Date(2524780800000)/",
      "ArrivalTime": null,
      "CanShowArrivalTime": false,
      "EarlyArrivalReason": null,
      "DurationInMinutes": null,
      "HasDuration": false,
      "Copay": null,
      "CanShowPayments": false,
      "ShortDate": "01/03/50",
      "IsTimeToBeDetermined": false,
      "IsHideVisitTime": false,
      "CanShowAppointmentTime": true,
      "TimeZone": "EDT",
      "Providers": [],
      "OtherProviders": [],
      "NumberOfOthers": 0,
      "PrimaryProvider": null,
      "PrimaryProviderName": null,
      "PrimaryDepartment": {
        "Id": "FAKE_DEPT_3",
        "Name": "Fake Department D",
        "Address": [
          "123 Department Ave",
          "Fake Town, FC 11111"
        ],
        "HasAddress": true,
        "PhoneNumber": "FAKE_PHONE_DEPT_3",
        "Instructions": [],
        "ShouldShowInstructions": false,
        "TimeZone": "EDT",
        "ArrivalLocation": "",
        "Specialty": {
          "Value": "00",
          "Title": "General",
          "TitleUtf8": null,
          "Abbreviation": "Gen"
        },
        "CanShowDrivingDirections": true,
        "IsPreadmissionLocation": false
      },
      "CanRequestCancel": false,
      "IsCanceled": false,
      "CanReschedule": false,
      "RescheduledDat": "",
      "IsDetailsEnabled": true,
      "ECheckIn": {
        "Status": {
          "Value": "",
          "Title": "",
          "Abbreviation": ""
        },
        "IsNotStarted": false,
        "IsInProgress": false,
        "IsComplete": false,
        "Barcode": "",
        "HasBarcodeStep": false,
        "ClinicSteps": [],
        "ECheckInSteps": [],
        "HasQuestionnaireLink": false,
        "IsAdmission": false,
        "IsSurgery": false,
        "IsQnrAfterBarcode": false,
        "IsConfirmationView": false,
        "SignUpLink": null,
        "HasSignUpLink": false,
        "IsRequiredForTelemedicine": false,
        "CanShow": false,
        "HasPaymentECheckInStep": false,
        "HasQuestionnaireStep": false,
        "IsInHelloPatientWindow": false
      },
      "CanShowECheckIn": false,
      "CanShowECheckInComplete": false,
      "IsECheckInComplete": false,
      "NextIncompleteVisitECheckInCsn": null,
      "IsEcheckInEnabled": true,
      "IsECheckInIncomplete": false,
      "CanECheckIn": false,
      "ShouldShowECheckInInGuideBanner": false,
      "CanShowAddToCalendar": true,
      "IsPastVisit": false,
      "HighlightDate": "1/3/2050",
      "IsDrivingDirectionsEnabled": true,
      "ConfirmationStatus": 2,
      "IsConfirmed": false,
      "IsCancelRequestSent": false,
      "CanDirectlyCancel": false,
      "IsUsingFallbackVisitTypeName": false,
      "ChiefComplaint": "",
      "Diagnoses": null,
      "HasSentUpgradeRequest": false,
      "CanSendUpgradeRequest": false,
      "IsUserInitiatedArrivalAllowed": false,
      "SelfArrivalMechanism": 0,
      "SelfArrivalBannerViewModel": null,
      "GeolocationArrival": 0,
      "ArrivalStatus": 0,
      "PatientNextStepInstructions": "",
      "ArrivalAdditionalActions": [],
      "IsProxyRequestMinorFormOn": false,
      "ProxyRequestMinorForm": "",
      "GuestPatientFirstName": null,
      "TelehealthMode": 0,
      "InProgress": false,
      "IsResidentialMed": false,
      "EncounterIsSurgery": false,
      "EncounterIsEDVisit": false,
      "IsPreadmission": false,
      "SurgeryTimeOfDay": null,
      "PreadmissionLocation": null,
      "Cases": null,
      "IsHovPreadmission": false,
      "HasProcedures": false,
      "NumberOfProcedures": 0,
      "SurgicalProcedures": null,
      "ComponentVisits": null,
      "HasComponentVisits": false,
      "HasPaymentInfo": false,
      "IsFullyPaid": true,
      "CompleteECheckInCount": 0,
      "TotalECheckInCount": 0
    },
    {
      "HasPaymentFeature": true,
      "HasQuestionnaireFeature": true,
      "HasNewPvdFeature": false,
      "PrimaryDate": "1/4/2050 08:30:00 AM",
      "CsnForECheckIn": "FAKE_CSN_4",
      "RescheduledDatString": null,
      "IsNoShow": false,
      "LeftWithoutSeen": false,
      "DischargeDate": null,
      "HasDownloadSummaryLink": false,
      "HasTransmitSummaryLink": false,
      "CanRedirectToApptDetails": false,
      "PastVisitBucket": null,
      "IsClinicalInformationAvailable": false,
      "OwnedBy": 0,
      "AdmissionDateRange": null,
      "IsApptDetailsEnabled": true,
      "IsRequestCancelEnabled": true,
      "IsDirectCancelEnabled": true,
      "IsRescheduleEnabled": true,
      "IsCopayEnabled": true,
      "IsVisitSummaryEnabled": true,
      "IsDownloadSummaryEnabled": true,
      "IsTransmitCEEnabled": true,
      "IsTransmitDirectEnabled": false,
      "IsDischargeInstrEnabled": true,
      "IsPatHandoutsEnabled": false,
      "IsIPReviewEnabled": false,
      "IsDischargeSummaryEnabled": true,
      "IsProviderLinkEnabled": true,
      "IsPreadmissionEnabled": true,
      "IsEcheckInCompleted": false,
      "Csn": "FAKE_CSN_4",
      "Id": "FAKE_ID_4",
      "ReferenceID": "",
      "OrganizationLinks": [],
      "PrimaryOrganizationLink": null,
      "Organization": {
        "OrganizationId": "FAKE_ORG_ID",
        "OrganizationIdentifier": null,
        "RelatedOrganizations": null,
        "HasChildOrgs": false,
        "CELocationId": null,
        "WebsiteName": null,
        "OrganizationName": "FAKE Health Organization",
        "MyChartAppName": null,
        "SsnLabel": null,
        "IsLocal": true,
        "LogoUrl": "https://fakeorg.example.com/logo.png",
        "TermsAndConditionsUrl": null,
        "ProxyTermsAndConditionsUrl": null,
        "Address": [
          "FAKE_PHONE_0",
          "123 Fake Street",
          "Suite 100",
          "Fake City, FC 12345",
          "Fakeland"
        ],
        "DisplayAddress": null,
        "ContactInformation": null,
        "UrlList": null,
        "IsSSO": false,
        "IncompleteH2GSetup": false,
        "LastEncounterInfo": null,
        "IsGeneric": false,
        "PayerOrgDetails": {
          "IsPayerOnly": false,
          "IsPayvider": false,
          "IsPayer": false,
          "IsPayerLicensedForMyChart": false,
          "PayerChildWebsiteName": "",
          "PayerCvgLogo": "FAKE_PAYER_LOGO",
          "PayerCvgLogoMagicId": null,
          "PayerCvgToken": "FAKE_PAYER_TOKEN",
          "PayerCvgName": "FAKE_PAYER_NAME"
        },
        "IsMyChartCentral": false
      },
      "EncodedOrgID": null,
      "Month": 1,
      "DateOfMonth": "4",
      "Year": "2050",
      "IsLocal": true,
      "IsNonEpic": false,
      "IsSingleProvider": true,
      "Telemedicine": null,
      "EVisit": null,
      "CanShowTelemedicine": false,
      "Dat": "FAKE_DAT_4",
      "Date": "Monday January 04, 2050",
      "Time": "08:30 AM",
      "IsAM": true,
      "IsClientTime": false,
      "ClientTimeZoneMarker": "EDT",
      "EncounterType": 1,
      "VisitTypeName": "Fake Procedure E",
      "Instant": "/Date(2524872600000)/",
      "ArrivalTime": null,
      "CanShowArrivalTime": false,
      "EarlyArrivalReason": null,
      "DurationInMinutes": null,
      "HasDuration": false,
      "Copay": null,
      "CanShowPayments": false,
      "ShortDate": "01/04/50",
      "IsTimeToBeDetermined": false,
      "IsHideVisitTime": false,
      "CanShowAppointmentTime": true,
      "TimeZone": "EDT",
      "Providers": [
        {
          "EncryptedId": "FAKE_PROVIDER_ENCRYPTED_0",
          "Name": "Dr. Jane Smith, MD",
          "Type": 1,
          "PhotoUrl": "https://fakeorg.example.com/doctor1.png",
          "PhotoLink": "https://fakeorg.example.com/doctor1.png",
          "WebPageUrl": "",
          "HasPhotoOnBlob": false,
          "PhotoBlobToken": "",
          "IsPerson": true,
          "Department": {
            "Id": "FAKE_DEPT_PROV_0",
            "Name": "Fake Gastroenterology Associates",
            "Address": [
              "123 Clinic Rd",
              "Fake City, FC 12345"
            ],
            "HasAddress": true,
            "PhoneNumber": "FAKE_PHONE_PROV_0",
            "Instructions": [],
            "ShouldShowInstructions": false,
            "TimeZone": "EDT",
            "ArrivalLocation": "",
            "Specialty": {
              "Value": "10",
              "Title": "Fake Specialty",
              "TitleUtf8": null,
              "Abbreviation": "FS"
            },
            "CanShowDrivingDirections": true,
            "IsPreadmissionLocation": false
          },
          "PhotoClass": "color4"
        }
      ],
      "OtherProviders": [],
      "NumberOfOthers": 0,
      "PrimaryProvider": {
        "EncryptedId": "FAKE_PROVIDER_ENCRYPTED_0",
        "Name": "Dr. Jane Smith, MD",
        "Type": 1,
        "PhotoUrl": "https://fakeorg.example.com/doctor1.png",
        "PhotoLink": "https://fakeorg.example.com/doctor1.png",
        "WebPageUrl": "",
        "HasPhotoOnBlob": false,
        "PhotoBlobToken": "",
        "IsPerson": true,
        "Department": {
          "Id": "FAKE_DEPT_PROV_0",
          "Name": "Fake Gastroenterology Associates",
          "Address": [
            "123 Clinic Rd",
            "Fake City, FC 12345"
          ],
          "HasAddress": true,
          "PhoneNumber": "FAKE_PHONE_PROV_0",
          "Instructions": [],
          "ShouldShowInstructions": false,
          "TimeZone": "EDT",
          "ArrivalLocation": "",
          "Specialty": {
            "Value": "10",
            "Title": "Fake Specialty",
            "TitleUtf8": null,
            "Abbreviation": "FS"
          },
          "CanShowDrivingDirections": true,
          "IsPreadmissionLocation": false
        },
        "PhotoClass": "color4"
      },
      "PrimaryProviderName": "Dr. Jane Smith, MD",
      "PrimaryDepartment": {
        "Id": "FAKE_DEPT_4",
        "Name": "Fake Gastroenterology Associates",
        "Address": [
          "123 Clinic Rd",
          "Fake City, FC 12345"
        ],
        "HasAddress": true,
        "PhoneNumber": "FAKE_PHONE_DEPT_4",
        "Instructions": [],
        "ShouldShowInstructions": false,
        "TimeZone": "EDT",
        "ArrivalLocation": "",
        "Specialty": {
          "Value": "10",
          "Title": "Fake Specialty",
          "TitleUtf8": null,
          "Abbreviation": "FS"
        },
        "CanShowDrivingDirections": true,
        "IsPreadmissionLocation": false
      },
      "CanRequestCancel": true,
      "IsCanceled": false,
      "CanReschedule": false,
      "RescheduledDat": "",
      "IsDetailsEnabled": true,
      "ECheckIn": {
        "Status": {
          "Value": "",
          "Title": "",
          "Abbreviation": ""
        },
        "IsNotStarted": false,
        "IsInProgress": false,
        "IsComplete": false,
        "Barcode": "",
        "HasBarcodeStep": false,
        "ClinicSteps": [],
        "ECheckInSteps": [],
        "HasQuestionnaireLink": false,
        "IsAdmission": false,
        "IsSurgery": false,
        "IsQnrAfterBarcode": false,
        "IsConfirmationView": false,
        "SignUpLink": null,
        "HasSignUpLink": false,
        "IsRequiredForTelemedicine": false,
        "CanShow": false,
        "HasPaymentECheckInStep": false,
        "HasQuestionnaireStep": false,
        "IsInHelloPatientWindow": false
      },
      "CanShowECheckIn": false,
      "CanShowECheckInComplete": false,
      "IsECheckInComplete": false,
      "NextIncompleteVisitECheckInCsn": null,
      "IsEcheckInEnabled": true,
      "IsECheckInIncomplete": false,
      "CanECheckIn": false,
      "ShouldShowECheckInInGuideBanner": false,
      "CanShowAddToCalendar": true,
      "IsPastVisit": false,
      "HighlightDate": "1/4/2050",
      "IsDrivingDirectionsEnabled": true,
      "ConfirmationStatus": 2,
      "IsConfirmed": false,
      "IsCancelRequestSent": false,
      "CanDirectlyCancel": false,
      "IsUsingFallbackVisitTypeName": false,
      "ChiefComplaint": "",
      "Diagnoses": null,
      "HasSentUpgradeRequest": false,
      "CanSendUpgradeRequest": false,
      "IsUserInitiatedArrivalAllowed": false,
      "SelfArrivalMechanism": 0,
      "SelfArrivalBannerViewModel": null,
      "GeolocationArrival": 0,
      "ArrivalStatus": 0,
      "PatientNextStepInstructions": "",
      "ArrivalAdditionalActions": [],
      "IsProxyRequestMinorFormOn": false,
      "ProxyRequestMinorForm": "",
      "GuestPatientFirstName": null,
      "TelehealthMode": 0,
      "InProgress": false,
      "IsResidentialMed": false,
      "EncounterIsSurgery": false,
      "EncounterIsEDVisit": false,
      "IsPreadmission": false,
      "SurgeryTimeOfDay": null,
      "PreadmissionLocation": null,
      "Cases": null,
      "IsHovPreadmission": false,
      "HasProcedures": false,
      "NumberOfProcedures": 0,
      "SurgicalProcedures": null,
      "ComponentVisits": null,
      "HasComponentVisits": false,
      "HasPaymentInfo": false,
      "IsFullyPaid": true,
      "CompleteECheckInCount": 0,
      "TotalECheckInCount": 0
    },
    {
      "HasPaymentFeature": true,
      "HasQuestionnaireFeature": true,
      "HasNewPvdFeature": false,
      "PrimaryDate": "1/5/2050 08:20:00 AM",
      "CsnForECheckIn": "FAKE_CSN_5",
      "RescheduledDatString": null,
      "IsNoShow": false,
      "LeftWithoutSeen": false,
      "DischargeDate": null,
      "HasDownloadSummaryLink": false,
      "HasTransmitSummaryLink": false,
      "CanRedirectToApptDetails": false,
      "PastVisitBucket": null,
      "IsClinicalInformationAvailable": false,
      "OwnedBy": 0,
      "AdmissionDateRange": null,
      "IsApptDetailsEnabled": true,
      "IsRequestCancelEnabled": true,
      "IsDirectCancelEnabled": true,
      "IsRescheduleEnabled": true,
      "IsCopayEnabled": true,
      "IsVisitSummaryEnabled": true,
      "IsDownloadSummaryEnabled": true,
      "IsTransmitCEEnabled": true,
      "IsTransmitDirectEnabled": false,
      "IsDischargeInstrEnabled": true,
      "IsPatHandoutsEnabled": false,
      "IsIPReviewEnabled": false,
      "IsDischargeSummaryEnabled": true,
      "IsProviderLinkEnabled": true,
      "IsPreadmissionEnabled": true,
      "IsEcheckInCompleted": false,
      "Csn": "FAKE_CSN_5",
      "Id": "FAKE_ID_5",
      "ReferenceID": "",
      "OrganizationLinks": [],
      "PrimaryOrganizationLink": null,
      "Organization": {
        "OrganizationId": "FAKE_ORG_ID",
        "OrganizationIdentifier": null,
        "RelatedOrganizations": null,
        "HasChildOrgs": false,
        "CELocationId": null,
        "WebsiteName": null,
        "OrganizationName": "FAKE Health Organization",
        "MyChartAppName": null,
        "SsnLabel": null,
        "IsLocal": true,
        "LogoUrl": "https://fakeorg.example.com/logo.png",
        "TermsAndConditionsUrl": null,
        "ProxyTermsAndConditionsUrl": null,
        "Address": [
          "FAKE_PHONE_0",
          "123 Fake Street",
          "Suite 100",
          "Fake City, FC 12345",
          "Fakeland"
        ],
        "DisplayAddress": null,
        "ContactInformation": null,
        "UrlList": null,
        "IsSSO": false,
        "IncompleteH2GSetup": false,
        "LastEncounterInfo": null,
        "IsGeneric": false,
        "PayerOrgDetails": {
          "IsPayerOnly": false,
          "IsPayvider": false,
          "IsPayer": false,
          "IsPayerLicensedForMyChart": false,
          "PayerChildWebsiteName": "",
          "PayerCvgLogo": "FAKE_PAYER_LOGO",
          "PayerCvgLogoMagicId": null,
          "PayerCvgToken": "FAKE_PAYER_TOKEN",
          "PayerCvgName": "FAKE_PAYER_NAME"
        },
        "IsMyChartCentral": false
      },
      "EncodedOrgID": null,
      "Month": 1,
      "DateOfMonth": "5",
      "Year": "2050",
      "IsLocal": true,
      "IsNonEpic": false,
      "IsSingleProvider": true,
      "Telemedicine": null,
      "EVisit": null,
      "CanShowTelemedicine": false,
      "Dat": "FAKE_DAT_5",
      "Date": "Tuesday January 05, 2050",
      "Time": "08:20 AM",
      "IsAM": true,
      "IsClientTime": false,
      "ClientTimeZoneMarker": "EDT",
      "EncounterType": 1,
      "VisitTypeName": "Fake Procedure F",
      "Instant": "/Date(2524963200000)/",
      "ArrivalTime": null,
      "CanShowArrivalTime": false,
      "EarlyArrivalReason": null,
      "DurationInMinutes": null,
      "HasDuration": false,
      "Copay": null,
      "CanShowPayments": false,
      "ShortDate": "01/05/50",
      "IsTimeToBeDetermined": false,
      "IsHideVisitTime": false,
      "CanShowAppointmentTime": true,
      "TimeZone": "EDT",
      "Providers": [
        {
          "EncryptedId": "FAKE_PROVIDER_ENCRYPTED_1",
          "Name": "Dr. Alex Johnson, PA-C",
          "Type": 1,
          "PhotoUrl": "https://fakeorg.example.com/doctor2.png",
          "PhotoLink": "https://fakeorg.example.com/doctor2.png",
          "WebPageUrl": "",
          "HasPhotoOnBlob": false,
          "PhotoBlobToken": "",
          "IsPerson": true,
          "Department": {
            "Id": "FAKE_DEPT_PROV_1",
            "Name": "Fake Orthopaedic Surgery Department",
            "Address": [
              "456 Hospital Blvd",
              "Fake Town, FT 67890"
            ],
            "HasAddress": true,
            "PhoneNumber": "FAKE_PHONE_PROV_1",
            "Instructions": [],
            "ShouldShowInstructions": false,
            "TimeZone": "EDT",
            "ArrivalLocation": "",
            "Specialty": {
              "Value": "191",
              "Title": "Fake Orthopaedics",
              "TitleUtf8": null,
              "Abbreviation": "FO"
            },
            "CanShowDrivingDirections": true,
            "IsPreadmissionLocation": false
          },
          "PhotoClass": "color3"
        }
      ],
      "OtherProviders": [],
      "NumberOfOthers": 0,
      "PrimaryProvider": {
        "EncryptedId": "FAKE_PROVIDER_ENCRYPTED_1",
        "Name": "Dr. Alex Johnson, PA-C",
        "Type": 1,
        "PhotoUrl": "https://fakeorg.example.com/doctor2.png",
        "PhotoLink": "https://fakeorg.example.com/doctor2.png",
        "WebPageUrl": "",
        "HasPhotoOnBlob": false,
        "PhotoBlobToken": "",
        "IsPerson": true,
        "Department": {
          "Id": "FAKE_DEPT_PROV_1",
          "Name": "Fake Orthopaedic Surgery Department",
          "Address": [
            "456 Hospital Blvd",
            "Fake Town, FT 67890"
          ],
          "HasAddress": true,
          "PhoneNumber": "FAKE_PHONE_PROV_1",
          "Instructions": [],
          "ShouldShowInstructions": false,
          "TimeZone": "EDT",
          "ArrivalLocation": "",
          "Specialty": {
            "Value": "191",
            "Title": "Fake Orthopaedics",
            "TitleUtf8": null,
            "Abbreviation": "FO"
          },
          "CanShowDrivingDirections": true,
          "IsPreadmissionLocation": false
        },
        "PhotoClass": "color3"
      },
      "PrimaryProviderName": "Dr. Alex Johnson, PA-C",
      "PrimaryDepartment": {
        "Id": "FAKE_DEPT_5",
        "Name": "Fake Orthopaedic Surgery Department",
        "Address": [
          "456 Hospital Blvd",
          "Fake Town, FT 67890"
        ],
        "HasAddress": true,
        "PhoneNumber": "FAKE_PHONE_DEPT_5",
        "Instructions": [],
        "ShouldShowInstructions": false,
        "TimeZone": "EDT",
        "ArrivalLocation": "",
        "Specialty": {
          "Value": "191",
          "Title": "Fake Orthopaedics",
          "TitleUtf8": null,
          "Abbreviation": "FO"
        },
        "CanShowDrivingDirections": true,
        "IsPreadmissionLocation": false
      },
      "CanRequestCancel": true,
      "IsCanceled": false,
      "CanReschedule": false,
      "RescheduledDat": "",
      "IsDetailsEnabled": true,
      "ECheckIn": {
        "Status": {
          "Value": "",
          "Title": "",
          "Abbreviation": ""
        },
        "IsNotStarted": false,
        "IsInProgress": false,
        "IsComplete": false,
        "Barcode": "",
        "HasBarcodeStep": false,
        "ClinicSteps": [],
        "ECheckInSteps": [],
        "HasQuestionnaireLink": false,
        "IsAdmission": false,
        "IsSurgery": false,
        "IsQnrAfterBarcode": false,
        "IsConfirmationView": false,
        "SignUpLink": null,
        "HasSignUpLink": false,
        "IsRequiredForTelemedicine": false,
        "CanShow": false,
        "HasPaymentECheckInStep": false,
        "HasQuestionnaireStep": false,
        "IsInHelloPatientWindow": false
      },
      "CanShowECheckIn": false,
      "CanShowECheckInComplete": false,
      "IsECheckInComplete": false,
      "NextIncompleteVisitECheckInCsn": null,
      "IsEcheckInEnabled": true,
      "IsECheckInIncomplete": false,
      "CanECheckIn": false,
      "ShouldShowECheckInInGuideBanner": false,
      "CanShowAddToCalendar": true,
      "IsPastVisit": false,
      "HighlightDate": "1/5/2050",
      "IsDrivingDirectionsEnabled": true,
      "ConfirmationStatus": 2,
      "IsConfirmed": false,
      "IsCancelRequestSent": false,
      "CanDirectlyCancel": true,
      "IsUsingFallbackVisitTypeName": false,
      "ChiefComplaint": "",
      "Diagnoses": null,
      "HasSentUpgradeRequest": false,
      "CanSendUpgradeRequest": false,
      "IsUserInitiatedArrivalAllowed": false,
      "SelfArrivalMechanism": 0,
      "SelfArrivalBannerViewModel": null,
      "GeolocationArrival": 0,
      "ArrivalStatus": 0,
      "PatientNextStepInstructions": "",
      "ArrivalAdditionalActions": [],
      "IsProxyRequestMinorFormOn": false,
      "ProxyRequestMinorForm": "",
      "GuestPatientFirstName": null,
      "TelehealthMode": 0,
      "InProgress": false,
      "IsResidentialMed": false,
      "EncounterIsSurgery": false,
      "EncounterIsEDVisit": false,
      "IsPreadmission": false,
      "SurgeryTimeOfDay": null,
      "PreadmissionLocation": null,
      "Cases": null,
      "IsHovPreadmission": false,
      "HasProcedures": false,
      "NumberOfProcedures": 0,
      "SurgicalProcedures": null,
      "ComponentVisits": null,
      "HasComponentVisits": false,
      "HasPaymentInfo": false,
      "IsFullyPaid": true,
      "CompleteECheckInCount": 0,
      "TotalECheckInCount": 0
    }
  ],
  "NextNDaysVisits": [],
  "InProgressVisits": [],
  "HighlightDays": [
    "1/1/2050",
    "1/1/2050",
    "1/2/2050",
    "1/3/2050",
    "1/4/2050",
    "1/5/2050"
  ],
  "HasPVG": false
}


// This should be the full HTML page of the test results page.
export const loadUpcomingVisits: MockData = {
  path: ['/MyChartPRD/Visits/VisitsList/LoadUpcoming'],
  response: new Response(JSON.stringify(visits))
}
