import { useCallback, useMemo, useRef, useState } from 'react';
import { AI_ENDPOINT, GITHUB_URL, HAS_LIVE_AI } from './config';
import { createProxyCompleter, runTurn as runAgentTurn } from './agent';
import { createSession, executeTool, TOOL_SPECS } from './tools';
import { describeResult, resultError, summarizeArgs } from './display';
import { IosSurface, type IosHandle } from './components/IosSurface';
import { DesktopSurface, type DesktopHandle } from './components/DesktopSurface';
import type { Surface, ToolRecord, TurnCallbacks } from './types';

/**
 * Demo shell.
 *
 * Owns the one thing both surfaces share: the session. The iOS app and the
 * Claude Desktop window read and write the *same* fictional record, so a refill
 * requested on the phone shows up in the desktop chat. That's the actual
 * product claim — one connector, whichever client you like — so the demo
 * shouldn't fake it with two isolated copies.
 *
 * Both surfaces stay mounted and are toggled with `hidden`, because switching
 * clients mid-conversation is the whole point of having two of them and a
 * remount would throw away the chat you just had.
 */

type Engine = 'live' | 'unavailable' | 'unconfigured';

const ENGINE_LABEL: Record<Engine, { text: string; title: string; cls: string }> = {
  live: {
    text: 'Live model',
    title: 'Every reply is generated by a real model call. There is no canned-response path.',
    cls: 'live',
  },
  unavailable: {
    text: 'Model unreachable',
    title: 'The demo model proxy is down, over quota, or rate limiting you. Try again in a moment.',
    cls: 'scripted',
  },
  unconfigured: {
    text: 'No model configured',
    title: 'This build has no AI endpoint set, so the demo cannot answer. Pass ?ai=<url> or set VITE_AI_ENDPOINT.',
    cls: 'scripted',
  },
};

const TRY_PROMPTS = [
  'Summarize my record and tell me what needs attention.',
  'Which lab values have been out of range more than once?',
  'Show me my chest X-ray and explain the report.',
  'What do I owe, and what did insurance actually cover?',
  'Request a refill of my atorvastatin.',
  'Find an appointment slot with Dr. Hibbert and book it.',
  'Draft a message asking billing for an itemized statement.',
  'Add my daughter Lisa as an emergency contact at (555) 636-7666.',
];

export function App() {
  // Bumping this key rebuilds both surfaces against a fresh session.
  const [sessionKey, setSessionKey] = useState(0);
  const session = useMemo(() => {
    const fresh = createSession();
    // The demo drops you into a connected account — the setup flow is the
    // product's, not the demo's, and making visitors click through it before
    // they can ask anything buries the part worth showing.
    executeTool(fresh, 'connect_instance', {});
    return fresh;
  }, [sessionKey]);

  const [surface, setSurface] = useState<Surface>('ios');
  const [engine, setEngine] = useState<Engine>(HAS_LIVE_AI ? 'live' : 'unconfigured');
  const [activity, setActivity] = useState<ToolRecord[]>([]);

  const iosRef = useRef<IosHandle | null>(null);
  const desktopRef = useRef<DesktopHandle | null>(null);

  const complete = useMemo(() => {
    if (HAS_LIVE_AI) return createProxyCompleter(AI_ENDPOINT);
    // Nothing to call. Fail loudly rather than inventing an answer.
    return async () => {
      throw new Error('no model endpoint is configured for this build');
    };
  }, []);

  const runTurn = useCallback(
    async (opts: {
      userText: string;
      history: { role: 'user' | 'assistant'; content: string }[];
      surface: Surface;
      skillAddition: string | null;
      memoryDigest: string | null;
      callbacks: TurnCallbacks;
    }) => {
      return runAgentTurn({
        session,
        userText: opts.userText,
        history: opts.history,
        complete,
        skillAddition: opts.skillAddition,
        memoryDigest: opts.memoryDigest,
        surface: opts.surface,
        callbacks: {
          onToolStart: opts.callbacks.onToolStart,
          onToolEnd: (record) => {
            setActivity((prev) => [record, ...prev].slice(0, 60));
            opts.callbacks.onToolEnd?.(record);
          },
          onError: () => setEngine('unavailable'),
          // Each surface renders its own dialog, so this passes straight
          // through — the phone's confirmation must not answer the desktop's.
          onConfirmWrite: opts.callbacks.onConfirmWrite,
        },
      });
    },
    [session, complete],
  );

  function runPrompt(text: string) {
    // Read the handle at click time, not at render time — the surfaces register
    // theirs in an effect, and App does not re-render when they do.
    const active = surface === 'ios' ? iosRef.current : desktopRef.current;
    active?.send(text);
  }

  function reset() {
    setActivity([]);
    setEngine(HAS_LIVE_AI ? 'live' : 'unconfigured');
    setSessionKey((k) => k + 1);
  }

  const badge = ENGINE_LABEL[engine];

  return (
    <>
      <div className="bg-canvas" aria-hidden="true">
        <div className="bg-blob a" />
        <div className="bg-blob b" />
      </div>

      <header className="demo-header">
        <div className="demo-header-inner">
          <a className="demo-back" href="./index.html">
            <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
              <path d="m15 18-6-6 6-6" />
            </svg>
            OpenRecord
          </a>
          <div className="demo-header-badges">
            <span className="demo-badge amber" title="Every record in this demo is invented. Homer Simpson is not a patient.">
              Fictional data
            </span>
            <span className={`engine-badge ${badge.cls}`} title={badge.title}>
              {badge.text}
            </span>
          </div>
          <div className="demo-header-actions">
            <button className="demo-btn ghost" onClick={reset}>
              Reset demo
            </button>
            <a className="demo-btn ghost" href={GITHUB_URL} target="_blank" rel="noopener noreferrer">
              GitHub
            </a>
          </div>
        </div>
      </header>

      <main className="demo-layout">
        <section className="demo-stage-col">
          <div className="surface-tabs" role="tablist" aria-label="Choose a client">
            <button
              className="surface-tab"
              role="tab"
              aria-selected={surface === 'ios'}
              onClick={() => setSurface('ios')}
            >
              <svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8">
                <rect x="6" y="2" width="12" height="20" rx="2.6" />
                <path d="M11 18.5h2" />
              </svg>
              iPhone app
            </button>
            <button
              className="surface-tab"
              role="tab"
              aria-selected={surface === 'desktop'}
              onClick={() => setSurface('desktop')}
            >
              <svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8">
                <rect x="2" y="3" width="20" height="14" rx="2" />
                <path d="M8 21h8M12 17v4" />
              </svg>
              Claude Desktop
            </button>
          </div>

          <div className="stage">
            <div className="stage-pane" hidden={surface !== 'ios'}>
              <IosSurface
                key={`ios-${sessionKey}`}
                session={session}
                runTurn={runTurn}
                onReady={(handle) => {
                  iosRef.current = handle;
                }}
              />
            </div>
            <div className="stage-pane" hidden={surface !== 'desktop'}>
              <DesktopSurface
                key={`desktop-${sessionKey}`}
                runTurn={runTurn}
                onReady={(handle) => {
                  desktopRef.current = handle;
                }}
              />
            </div>
          </div>
        </section>

        <aside className="demo-side">
          <div className="side-card">
            <h1 className="side-title">A real product, a fake patient</h1>
            <p className="side-copy">
              This is the actual OpenRecord experience running in your browser — the same onboarding, the same
              agent loop, the same <strong>{TOOL_SPECS.length} MyChart tools</strong>. The only difference is
              that the tools read a fictional record instead of a live Epic portal.
            </p>
            <p className="side-copy">
              Both clients share one session. Request a refill on the phone, then switch to Claude Desktop and
              ask what changed.
            </p>
          </div>

          <div className="side-card">
            <div className="side-card-head">
              <h2 className="side-heading">Tool calls</h2>
              <span className="activity-count">{activity.length}</span>
            </div>
            <p className="side-copy small">Every call the assistant makes, as it happens.</p>
            {activity.length === 0 ? (
              <p className="activity-empty">Ask a question and the calls show up here.</p>
            ) : (
              <ul className="activity-list">
                {activity.map((record, i) => {
                  const meta = describeResult(record.result);
                  const args = summarizeArgs(record.args);
                  const error = resultError(record.result);
                  return (
                    <li className={`activity-row${meta.ok ? '' : ' failed'}`} key={`${record.tool}-${i}`}>
                      <div className="activity-top">
                        <code className="activity-tool">{record.tool}</code>
                        <span className="activity-ms">{record.ms}ms</span>
                      </div>
                      {args && <p className="activity-args">{args}</p>}
                      <p className="activity-meta">{error ? `→ ${error}` : `→ ${meta.label}`}</p>
                    </li>
                  );
                })}
              </ul>
            )}
          </div>

          <div className="side-card">
            <h2 className="side-heading">Try asking</h2>
            <ul className="try-list">
              {TRY_PROMPTS.map((prompt) => (
                <li key={prompt}>
                  <button className="try-prompt" onClick={() => runPrompt(prompt)}>
                    {prompt}
                  </button>
                </li>
              ))}
            </ul>
          </div>

          <div className="side-card muted">
            <h2 className="side-heading">What is not real</h2>
            <ul className="fact-list">
              <li>The patient, the hospital, and every number in the record are invented.</li>
              <li>No portal is contacted and nothing is stored — reloading starts over.</li>
              <li>The UI is a faithful re-creation, not the shipped binary.</li>
              <li>
                Every reply is generated by a real model call — there are no pre-written responses. If the model
                can&rsquo;t be reached, the demo says so; the badge up top shows the connection state.
              </li>
            </ul>
            <p className="side-copy small">
              Nothing here is medical advice, and the real product isn&rsquo;t either — it reads your record and
              helps you ask better questions.
            </p>
          </div>

          <div className="side-card cta">
            <h2 className="side-heading">Run it on your own record</h2>
            <p className="side-copy small">
              Join the waitlist and we&rsquo;ll tell you the moment you can point it at your own records.
            </p>
            <div className="side-cta-row">
              <a className="demo-btn primary" href="./index.html#waitlist">
                Join the waitlist
              </a>
              <a className="demo-btn ghost" href={GITHUB_URL} target="_blank" rel="noopener noreferrer">
                Source
              </a>
            </div>
          </div>
        </aside>
      </main>
    </>
  );
}
