#!/usr/bin/env bash
# Build and deploy the OpenRecord splash page + interactive demo to S3 + CloudFront.
#
# Follows the standard Fan Pier Labs static-site pattern:
#   - Private S3 bucket `openrecord-fanpierlabs-com` (us-east-2), served via CloudFront OAC
#   - CloudFront distribution fronts openrecord.fanpierlabs.com (wildcard *.fanpierlabs.com cert)
#
# Three things get uploaded:
#   index.html          the marketing splash — hand-written, no build step
#   demo/ → dist/       the React + TypeScript demo, built with Vite
#   icons + og-image    share-preview and PWA assets, generated by generate-assets.sh
#
# Content types are set explicitly. S3 guesses `binary/octet-stream` for unknown
# extensions, and a .js served as anything but a JavaScript MIME type is refused
# by the browser's module loader — which would break the demo while leaving the
# splash page looking fine.
#
# Usage:  AWS_PROFILE=fanpierlabs ./deploy.sh
set -euo pipefail

PROFILE="${AWS_PROFILE:-fanpierlabs}"
REGION="${REGION:-us-east-2}"
BUCKET="${BUCKET:-openrecord-fanpierlabs-com}"
DIST_ID="${DIST_ID:-EXUZ8GHUQ9ULF}"   # CloudFront distribution for openrecord.fanpierlabs.com
SRC_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BUILD_DIR="$SRC_DIR/dist"

AWS=(aws --profile "$PROFILE" --region "$REGION")

content_type_for() {
  case "$1" in
    *.html) echo "text/html; charset=utf-8" ;;
    *.js)   echo "text/javascript; charset=utf-8" ;;
    *.css)  echo "text/css; charset=utf-8" ;;
    *.svg)  echo "image/svg+xml" ;;
    *.json) echo "application/json; charset=utf-8" ;;
    *.woff2) echo "font/woff2" ;;
    *)      echo "application/octet-stream" ;;
  esac
}

# Build output: the key differs from the source path (dist/ is stripped) and the
# cache policy differs per file, so both are passed in.
upload_built() {
  local path="$1" key="$2" cache="$3"
  echo "    $key"
  "${AWS[@]}" s3 cp "$path" "s3://$BUCKET/$key" \
    --content-type "$(content_type_for "$path")" \
    --cache-control "$cache" \
    --only-show-errors
}

# Checked-in site assets: icons, share card, and PWA manifest. Each names its own
# content-type — S3 guesses from the extension, and it guesses wrong for
# .json-as-manifest and .svg. Long max-age is safe: these are content-stable, and
# a change ships with an invalidation below.
upload() {
  local file="$1" ctype="$2"
  echo "    $file"
  "${AWS[@]}" s3 cp "$SRC_DIR/$file" "s3://$BUCKET/$file" \
    --content-type "$ctype" \
    --cache-control "public, max-age=86400" \
    --only-show-errors
}

echo "==> Building the demo (typecheck + vite build)"
( cd "$SRC_DIR/demo" && npx tsc --noEmit -p tsconfig.json && npx vite build )

if [ ! -f "$BUILD_DIR/demo.html" ]; then
  echo "!! Build did not produce $BUILD_DIR/demo.html" >&2
  exit 1
fi

echo "==> Uploading the splash page"
# Short TTL: the HTML is the entry point and must pick up new asset hashes.
upload_built "$SRC_DIR/index.html" "index.html" "public, max-age=300"
# The legal pages are linked from the splash page and the app stores, so they
# ship with it — a 404 here is a broken promise, not a broken page.
upload_built "$SRC_DIR/privacy.html" "privacy.html" "public, max-age=300"
upload_built "$SRC_DIR/terms.html" "terms.html" "public, max-age=300"

echo "==> Uploading the demo"
upload_built "$BUILD_DIR/demo.html" "demo.html" "public, max-age=300"

# Vite fingerprints asset filenames, so they can be cached hard and forever.
while IFS= read -r file; do
  upload_built "$file" "assets/$(basename "$file")" "public, max-age=31536000, immutable"
done < <(find "$BUILD_DIR/assets" -type f 2>/dev/null || true)

echo "==> Uploading icons, share card, and manifest"
upload og-image.png         "image/png"
upload icon.svg             "image/svg+xml"
upload icon-192.png         "image/png"
upload icon-512.png         "image/png"
upload apple-touch-icon.png "image/png"
upload favicon.ico          "image/x-icon"
upload manifest.json        "application/manifest+json"

echo "==> Invalidating CloudFront ($DIST_ID)"
# The HTML entry points and the fixed-name site assets. Vite's hashed assets are
# new paths every build, so they never need invalidating.
"${AWS[@]}" cloudfront create-invalidation \
  --distribution-id "$DIST_ID" \
  --paths "/index.html" "/demo.html" "/privacy.html" "/terms.html" "/" "/og-image.png" "/icon.svg" \
          "/icon-192.png" "/icon-512.png" "/apple-touch-icon.png" "/favicon.ico" "/manifest.json" \
  --query 'Invalidation.{Id:Id,Status:Status}' --output table

echo ""
echo "==> Done."
echo "    https://openrecord.fanpierlabs.com/"
echo "    https://openrecord.fanpierlabs.com/demo.html"
