/**
 * Demo boot and orchestration.
 *
 * Owns the one thing both surfaces share: the session. The iOS app and the
 * Claude Desktop window read and write the *same* fictional record, so a refill
 * requested on the phone shows up in the desktop chat. That's the actual
 * product claim — one connector, whichever client you like — so the demo
 * shouldn't fake it with two isolated copies.
 */

import { AI_ENDPOINT, HAS_LIVE_AI, GITHUB_URL } from './config.js';
import { createSession, TOOL_SPECS } from './tools.js';
import { runTurn as runAgentTurn, createProxyCompleter } from './agent.js';
import { createIosSurface } from './ios.js';
import { createDesktopSurface } from './desktop.js';
import { el, clear, describeResult, summarizeArgs } from './ui.js';


const stage = document.getElementById('stage');
const activityList = document.getElementById('activity-list');
const activityCount = document.getElementById('activity-count');
const activityEmpty = document.querySelector('.activity-empty');
const engineBadge = document.getElementById('engine-badge');
const tabs = document.querySelectorAll('.surface-tab');
const resetBtn = document.getElementById('reset-demo');
const skipBtn = document.getElementById('skip-setup');
const toolTotal = document.getElementById('tool-total');
const tryPrompts = document.getElementById('try-prompts');

let session = createSession();
let surface = null;
let surfaceKind = 'ios';
let callCount = 0;

const complete = HAS_LIVE_AI ? createProxyCompleter(AI_ENDPOINT) : null;

/* ------------------------------------------------------------------ *
 * Engine badge — be honest about which engine is answering
 * ------------------------------------------------------------------ */

function setEngine(mode) {
  const config = {
    live: { text: 'Live model', title: `Answers generated by ${AI_ENDPOINT ? 'the demo model proxy' : 'a live model'}.`, cls: 'live' },
    scripted: {
      text: 'Scripted replies',
      title: 'No model endpoint is configured, so replies are pre-written. The tool calls and the data are still real.',
      cls: 'scripted',
    },
    fallback: {
      text: 'Model unavailable — scripted',
      title: 'The demo model proxy is down or rate limited. Tool calls still run for real; the wording is pre-written.',
      cls: 'scripted',
    },
  }[mode];
  engineBadge.textContent = config.text;
  engineBadge.title = config.title;
  engineBadge.className = `engine-badge ${config.cls}`;
}

setEngine(HAS_LIVE_AI ? 'live' : 'scripted');

/* ------------------------------------------------------------------ *
 * Activity panel — every tool call, both surfaces
 * ------------------------------------------------------------------ */

function logToolCall(record) {
  const meta = describeResult(record.result);
  const args = summarizeArgs(record.args);
  const row = el(
    'li',
    { class: `activity-row${meta.ok ? '' : ' failed'}` },
    el('div', { class: 'activity-top' },
      el('code', { class: 'activity-tool', text: record.tool }),
      el('span', { class: 'activity-ms', text: `${record.ms}ms` })
    ),
    args ? el('p', { class: 'activity-args', text: args }) : null,
    el('p', { class: 'activity-meta', text: meta.ok ? `→ ${meta.label}` : `→ ${record.result.error}` })
  );
  activityList.prepend(row);
  callCount++;
  activityCount.textContent = String(callCount);
  activityEmpty.hidden = true;
  while (activityList.children.length > 60) activityList.lastChild.remove();
}

function clearActivity() {
  clear(activityList);
  callCount = 0;
  activityCount.textContent = '0';
  activityEmpty.hidden = false;
}

/* ------------------------------------------------------------------ *
 * Turn runner shared by both surfaces
 * ------------------------------------------------------------------ */

async function runTurn({ userText, history, callbacks = {}, skillAddition, memoryDigest, surface: surfaceName }) {
  return runAgentTurn({
    session,
    userText,
    history,
    complete,
    skillAddition,
    memoryDigest,
    surface: surfaceName,
    callbacks: {
      onToolStart: callbacks.onToolStart,
      onToolEnd: (record) => {
        logToolCall(record);
        callbacks.onToolEnd?.(record);
      },
      onFallback: () => setEngine('fallback'),
    },
  });
}

/* ------------------------------------------------------------------ *
 * Surface switching
 * ------------------------------------------------------------------ */

/**
 * Both surfaces are built once and toggled with `hidden`, rather than being
 * re-created on every tab click. Switching clients mid-conversation is the
 * whole point of having two of them, and a re-mount would throw away the chat
 * you just had.
 */
const panes = {
  ios: el('div', { class: 'stage-pane' }),
  desktop: el('div', { class: 'stage-pane', hidden: true }),
};
const surfaces = {};

function buildSurfaces() {
  surfaces.ios = createIosSurface({ mount: panes.ios, runTurn, session });
  surfaces.desktop = createDesktopSurface({ mount: panes.desktop, runTurn, session });
  surface = surfaces[surfaceKind];
}

function showSurface(kind) {
  surfaceKind = kind;
  surface = surfaces[kind];
  stage.dataset.surface = kind;
  panes.ios.hidden = kind !== 'ios';
  panes.desktop.hidden = kind !== 'desktop';
  for (const tab of tabs) tab.setAttribute('aria-selected', String(tab.dataset.surface === kind));
  updateSkipButton();
}

function updateSkipButton() {
  const onboarding = surface?.isOnboarding?.() ?? false;
  skipBtn.hidden = !onboarding;
}

for (const tab of tabs) {
  tab.addEventListener('click', () => {
    if (tab.dataset.surface === surfaceKind) return;
    showSurface(tab.dataset.surface);
  });
}

tryPrompts.addEventListener('click', (event) => {
  const button = event.target.closest('.try-prompt');
  if (!button) return;
  // Onboarding has no composer to type into, so jump the visitor to the point
  // where the question can actually be asked.
  if (surface.isOnboarding()) {
    if (surfaceKind === 'ios') surface.skipOnboarding();
    else surface.skipSetup();
    updateSkipButton();
  }
  surface.send(button.textContent.trim());
});

skipBtn.addEventListener('click', () => {
  if (surfaceKind === 'ios') surface.skipOnboarding();
  else surface.skipSetup();
  updateSkipButton();
});

resetBtn.addEventListener('click', () => {
  session = createSession();
  clearActivity();
  setEngine(HAS_LIVE_AI ? 'live' : 'scripted');
  buildSurfaces();
  showSurface(surfaceKind);
});

// The skip button's visibility depends on screen state the surfaces own, and
// they don't emit change events. A cheap poll beats threading a callback
// through every screen transition.
setInterval(updateSkipButton, 400);

toolTotal.textContent = String(TOOL_SPECS.length);
document.querySelectorAll('[data-github]').forEach((node) => node.setAttribute('href', GITHUB_URL));

stage.append(panes.ios, panes.desktop);
buildSurfaces();
showSurface('ios');
